baseURL = "https://step-functions-workshop.go-aws.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Introduction to Step Functions - Workshop"
theme = "learn"
uglyurls = true
# googleAnalytics = "UA-129511631-2"
sectionPagesMenu = "main"
pygmentsCodeFences = true
#pygmentsCodeFencesGuessSyntax = true
#pygmentsStyle = "monokai"


[blackfriday]
hrefTargetBlank = true

[params]
themeVariant = "mine"
showVisitedLinks = false
author = "Gabe Hollombe"
description = "AWS Step Functions / AWS Lambda / Workshop"
disableSearch = true
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=true


[[menu.shortcuts]]
name = "<i class='fab fa-twitter fa-lg'></i> @gabehollombe"
identifier = "tw"
url = "https://twitter.com/intent/user?screen_name=gabehollombe"
weight = 1

[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
page = [ "HTML", "AMP"]